### ISSUE TITLE
Random and color init moving else where

### ISSUE THREAD

**Issue by codyswanner** [MicahWW/Python-Games#12]
Random seed in TicTacToe.py -> __init__() may be unnecessary.  Look for alternative places to initialize random seed, and any potential interactions with other files.

**Comment by MicahWW** [comment]
With the addition of color and the below lines being added, they should also look at finding a different spot to run.

```
if os.name == "nt":
	os.system('color')
```

**Comment by MicahWW** [comment]
Looking at the Python [docs for Python 2.7](https://python.readthedocs.io/en/v2.7.2/library/random.html) says the below about seeding random:

> current system time is also used to initialize the generator when the module is first imported.

This means by importing random it gets seeded and is not necessary to add code to seed. Through some testing, Python 3 exhibits the same behavior but doesn't mention it in the docs. With that random.seed() can be completely removed from the program.
