### ISSUE TITLE
Clean Exits

### ISSUE THREAD

**Issue by codyswanner** [MicahWW/Python-Games#23]
We should add a way for players to exit the game mid-round, for instance, exit a game of checkers before the end of the game.

This is currently tied to Tic-Tac-Toe project, but should be applied to all games in the catalog.

**Comment by codyswanner** [comment]
Because this applies to all games, this issue has been added to the projects for all games.  (Hopefully the upcoming Tic-Tac-Toe merge doesn't close it.)

**Comment by MicahWW** [comment]
@codyswanner it closed it in each game.
