### ISSUE TITLE
Communicating preference strength

### ISSUE THREAD

**Issue by codyswanner** [MicahWW/Python-Games#71]
Less of a code issue as a communication idea -- as I was writing "this is a hill I will die on" about a detail in my last commit it occurred to me that "this is a hill I will die on" is a lot of words and it might be nice to have a shorthand for "I feel very strongly about this" or "eh, I don't really care either way" or "I actively dislike my own solution, please offer suggestions/help," all of which seem to be common sentiments on this project (at least from me).

Maybe just a scale out of 10?  If we put something like "intensity 1" to mean "I'm really unsure here, suggestions wanted" and "intensity 10" to mean "I will literally leave/kick you from the project if you don't get on board with this" maybe that would communicate the same thing in a lot fewer words? (I have yet to reach a 10, the quote that inspired this paragraph was like an 8, which is not really well communicated by "hill I will die on," which is another good reason for this to exist.)

The strength on this issue is "intensity 4," I would like this to be a thing but like, I'm not confident in my specific implementation and would be open to discussion.

**Comment by codyswanner** [comment]
Maybe "PS: 1" to "PS: 10" for "preference strength"?  I feel like there's some English word that more accurately captures the thing I'm trying to get at but my sleepy brain can't grab onto it 😄

**Comment by MicahWW** [comment]
There are so many words here without much actually happening.
Are you trying to find a way to say how strongly you feel about something?
